// const color = prompt("zadej barvu");
// console.log(color);
// const body = document.querySelector("body");
// body.style.backgroundColor = color;
// let f = "Milan";
// console.log(f);
// f = prompt("zadej jmeno");
// console.log(`krestni jsmeno ${f}`);
alert("pozor");
confirm("jsi starsi 18");
let h1 = document.getElementById("h111");
let h2 = document.querySelector("#h111");
let h3 = document.querySelector(".h111");
let h4 = document.querySelector("h1");
console.log(h1);
console.log(h2);
console.log(h3);
console.log(h4);
h1.style.fontSize = "40px";
h2.style.margin = "52px";
h3.style.backgroundColor = "pink";
h4.style.color = "red";
let color = prompt("zadej barvu");
let body = document.querySelector("body");
body.style.backgroundColor = color;
