const people = parseInt(prompt("zadej pocet lidi"));
const value = parseInt(prompt("zadej utratu"));
const tip = parseInt(prompt("zadej spropitne"));
console.log(people, value, tip);
const h1 = document.createElement("h1");
h1.textContent = "Restaurace";
const p1 = document.createElement("p");
p1.innerHTML = `Pocet lidi:<br>${people} ks`;
const p2 = document.createElement("p");
p2.innerHTML = `Utrata celkem:<br>${value} Kc`;
const p3 = document.createElement("p");
p3.innerHTML = `Spropitne:<br>${tip}%`;
const sec = document.querySelector(".restaurant");
const p4 = document.createElement("p");
const tipCount = (value * tip) / 100;
const totalValue = value + tipCount;
const cena1 = totalValue / people;
const cena = (value + (value * tip) / 100) / people;
console.log(tipCount, totalValue, cena);
p4.innerHTML = `Platba celkem na jednoho:<br> ${cena} Kc`;
sec.append(h1);
sec.append(p1);
sec.append(p2);
sec.append(p3);
sec.append(p4);
